---
title: "Class Objectives"
format: docx
editor: visual
---

## Goals of this document

We will treat this class more like a job. There will not be tests or quizzes. Rather we will have conversations where we discuss how you are doing, and what you could improve on. You will reflect on your work, I will reply and we will discuss your grade from there.

We can discuss amendment of objectives as well, especially your personal objectives.

## Basic objectives

Over the course it is expected you will:

**Technically**

1.  Understand and implement the basic R-Studio -\> GitHub workflow; be able to collaborate using GitHub.
2.  Work in Quarto files; be able to adjust format and make output look nice.
3.  Complete https://swcarpentry.github.io/r-novice-gapminder/index.html
4.  Develop slideshow and website.
5.  Use code to further your own research.

**Communications**

1.  Provide respectful feedback in class and on Slack.
2.  Assist with issues on in class and on Slack.

## Personal objectives

-   Write everything in Quarto files
-   Find and work through tutorials about pharmaceutical data in R
-   Create workflowR website https://workflowr.github.io/workflowr/

## Progress tracking

-   Met week of February 6, 2024 for initial conversation

## Jessica's Class Reflection 3/14/24

So far in this class I am pleasantly surprised at how much I have learned to do in R. I am currently less nervous whenever I open the software and more excited on solving the problems I come across (The Errors!! lol). There are small tricks I have learned from others in class as well as through my research and video tutorials. Since I am pretty new to R I do feel a little behind compared to other students in knowing what everything means and what packages can give them what they are looking for. I also don't have raw data to work with like other students so I am unable to create cool figures like they have been doing. Good news is I am joining Dr. Campos Lab and still waiting for her to send me data to play with so eventually I will get there. If I had to grade myself so far, due to not knowing as much as others I would give myself a B+. I am hoping in time when I have more data and can solve errors a lot better I will feel like more of an A. :)

## Jessica Class Reflection 4/29/24

Most of this time in the past month was taken up with trying to complete the code challenge, and I must say that even though it was soooooooo hard to do, I learned a lot about coding and the different steps it takes to develop your data and put it in a way like a graph. Personally, I still don't understand why there isn't certain functions that make it easier to just drag and drop or just say something to R and have it do it but ah that's the complexity of coding. Anyways, reflecting on my experience in doing the code challenge, I feel as though, even though it took a very long time, I am proud that I was able to complete it, being a new coder and all. I honestly didn't have faith in myself. However, once I started going step by step, function by function, I saw how things were starting to come together. I still struggle in a lot of areas, mainly in knowing what code gives me what I am thinking of but that will come with time. Overall, I feel as though i did really good with the code challenge and even though it was really hard and took so much time, in the end it was beneficial. Looking back at my workflow I am excited that I finally got data! I am working on changing my whole website to now match my Thesis Lab and what my advisor has told me I will be working on in the summer (Which I am so excited for)! Due to me kinda restarting I do feel slightly behind but I know I just need a couple days to catch up and start developing my charts with the data the way that I want to. I will try doing a violin plot but I'm not sure how it will turn out, either way I will try. Currently I feel as though I am getting better but still working to catch up to everyone levels so I think I'm at about a B+ or A-.
